---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 2.3.x
  values:
    configInline:
      address-pools:
        - name: tcd
          protocol: layer2
          addresses:
            - '134.226.83.27/32'
            - '134.226.83.67/32'
            - 134.226.83.100-134.226.83.107
