---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: docs
spec:
  image: ghcr.io/netsoc/docs
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: docs
spec:
  imageRepositoryRef:
    name: docs
  filterTags:
    pattern: '^[a-fA-F0-9]{8}-(?P<time>\d+)Z$'
    extract: '$time'
  policy:
    numerical:
      order: asc
