---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: acme@netsoc.tcd.ie
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-account-keys
      key: tls-staging.key
    solvers:
      - dns01:
          rfc2136:
            nameserver: powerdns-udp.default
            tsigKeyName: 'cert-manager.'
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: powerdns-tsig
              key: cert-manager.key
        selector:
          dnsZones: ['netsoc.ie']
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressTemplate:
              metadata:
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.tls: 'true'
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: acme@netsoc.tcd.ie
    server: https://acme-v02.api.letsencrypt.org/directory
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-account-keys
      key: tls.key
    solvers:
      - dns01:
          rfc2136:
            nameserver: powerdns-udp.default
            tsigKeyName: 'cert-manager.'
            tsigAlgorithm: HMACSHA512
            tsigSecretSecretRef:
              name: powerdns-tsig
              key: cert-manager.key
        selector:
          dnsZones: ['netsoc.ie']
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressTemplate:
              metadata:
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.tls: 'true'
