apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuers.yaml
secretGenerator:
- name: letsencrypt-account-keys
  files:
  - tls-staging.key=secrets/account-staging.key
  - tls.key=secrets/account.key
- name: powerdns-tsig
  files:
  - cert-manager.key=secrets/pdns-cert-manager.bin
- name: cloudflare-api
  files:
  - api-token=secrets/cloudflare-api-token.bin
