apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuers.yaml
secretGenerator:
- name: letsencrypt-account-keys
  namespace: cert-manager
  files:
  - tls-staging.key=account-staging.key
  - tls.key=account.key
- name: powerdns-tsig
  namespace: cert-manager
  files:
  - cert-manager.key=pdns-cert-manager.key
