apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: dex-extras
  values:
    image:
      repository: ghcr.io/netsoc/dex
      tag: 2.30.0-98ce910c-netsoc

    ingress:
      enabled: true
      tls:
        - hosts: [dex.netsoc.ie]
          secretName: tls-main
      hosts:
        - host: dex.netsoc.ie
          paths:
            - path: /
              pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'

    env:
      KUBERNETES_POD_NAMESPACE: default
    config:
      issuer: https://dex.netsoc.ie

      storage:
        type: kubernetes
        config:
          inCluster: true

      frontend:
        issuer: Netsoc
        logoURL: https://www.netsoc.ie/assets/images/netsoc-logo.svg
