apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webspaces
resources:
- dnsmasq
- lxd8s
- webspaced
- octolxd.yaml
configMapGenerator:
- name: kubelan
  files: [kubelan.yaml]
  options:
    disableNameSuffixHash: true
