apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octolxd
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://devplayer0.github.io/charts/
      chart: octolxd
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: devplayer0
        namespace: flux-system
  values:
    ingress:
      enabled: true
      tls:
        - hosts: [octolxd.netsoc.ie]
          secretName: tls-main
      hosts:
        - host: octolxd.netsoc.ie
          paths:
            - path: /
              pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'

    config:
      log_level: DEBUG
