backend:
    secrets:
        stripePrivateKey: ENC[AES256_GCM,data:kmFVtHvOi+n7ZvVI/FN4Bdn/5jKX2N0xltpN9zxmJGqZgj+oxcIRin+xwlXsa35NvKCuui8m5W3iPaF1yE5eOiOkKndacTvGorBBMNLAApfMHNQ9vapbQU5TCUhKzXj1/mcSvkuXTFCDSXc=,iv:ePqE0XuH0jgiyFn0wmPjJnX7D8SwuW/W9hPIV710r44=,tag:GfvqkE6AVWGiZu6EFuzt/A==,type:str]
        stripeEndpointSecret: ENC[AES256_GCM,data:2UVab9O2amhdL/83PbFs8hKKafYtWVBWwzFoxP3q43hD6oo4GT0=,iv:kZaLK9QexML0ERl+SuUTtZV0kpt8zX+skflgpnXD1Sw=,tag:LuSlbSS+Qn13MxyQB/ACMQ==,type:str]
        iamJWT: ENC[AES256_GCM,data:YSBh3FTYWAYDb4fz2Az0nJcKZpjtk0nbkYs3T0LRqak5wZdY6y0l4niyMBg54p7ZCDNmSJZwu+It7LdZ1/91cMYDsBUZts5T8ffMGChHS3ZpuF67nMO+O3Wc1AXMiOB0qNn3BPWoavzmYVqnAMqtbkJu1DdXcpQApsJsPv0SfSCzDu4sKrkKviw3l0vCWq9bwQHDOq65pBJw4s0jQF4hemVSfegt7nMCdCSWYfEinTxyr/o412RTYPaIZcoN2kQKs/Nh4tSwlh5AFammCCZhegUWZrczX1EREv0rKajhnTNNxL8KGJRChLKU+NXpbUkhyvvb/BayNwhsLL7wIFdoucs/3pH16An3CBEWOw==,iv:aGYF9fKxA1IieOcOzfgHP49I86fXNhGy5s8abG5Qm8s=,tag:ILynMzqbCPpbh1lfJTZikw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-16T01:51:09Z"
    mac: ENC[AES256_GCM,data:Wxzm6W+V+6Sg9ilu+75lBTCgWjulCjYps2ycQIiiqeqp80zQz4Ya2EVW5CbSmzAzDhG5caLoNp3wgY5PMdKa7rkp+bicmc7IzGWB5fr9nooxNddNCwoZm4H87TudoUHv7HpTH6Sjn5DfkaXFYcyXer7UgStZO/tMFby8R1grm3Q=,iv:2qLrcuUvKTsv/oWI55/zw8CKXzgOVe6YyVw/A8TU/ss=,tag:FMEXaby4MPKjqm89sGeoJg==,type:str]
    pgp:
        - created_at: "2021-06-16T01:51:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQwAjPA1b2fLviYvDFzDSQjW/X+u2IFqac35K6yJxA+awnO3
            6Cf0nII2U9KfGkXLwLZlzk5PTAI2lLKdOnfle4q55jApguyAOo4dY9goREuYc1QJ
            HXaRa4eJlwCbr6SvqE5FI2y0vCNoi0sg7Y0jIEzvaE2gu4w48lbdoxvE54P/HPnT
            m0X/lgii+ddiKvFbg9eymdZg1a4unrCTM9CPj3A74+cAm+yHtOcDZrPc3aGrhiXF
            81S6R70W7IPwulROcd4tNJIwkO470Wb2ixSn22AGyVIM7/OOSeiuSUVk+Zhyvu1h
            xQEy0T7JAOI83Zwd5Moal9ldTbA9pYgVi4h25Yx38Om2t26VdMTuNMeJUbnbXf/h
            kTJ2/4HqKM7T7BbOwrZbikBPY/F0QI3VrWloc1t1Pf4CFABYDXZl+blHUiDSGdiT
            /5fqNuwxFXDVKJJjzo4YatOyYA6YqWIrGNWWkM4y9GpWBTuQptsD7O2sgG95VgTC
            SCMoG0PtU+rlGnY21os10l4BhZoFIsNGIc3KULnvkYdmxzdRh9MoDVI7IjMJRutp
            ppsaOmZnAT/17E2+b2BTjLbgpwsHFEKUgWBUbPFsY69+t4PFu4OCQPdNJyset3zj
            ftT9cpZ9I3SAWJUlvjz/
            =zbPe
            -----END PGP MESSAGE-----
          fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    unencrypted_suffix: _unencrypted
    version: 3.7.1
