---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 2Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  volumeName: vaultwarden
  storageClassName: longhorn
