env:
    ADMIN_TOKEN: ENC[AES256_GCM,data:67CAZSgAMwNYwckeKEfE5Y0S4T4IIno/gJ3NLamz6sSyuSoZm4Un1/91BNkdvfn3glEyBjAeSwiLy1IXd7Bk/w==,iv:0az2lWuibbpv7YKOSxSmc2WfLk3WGEIBX/wI5mF1DTM=,tag:1KGThfoWeSDy1IFySEa5jQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:N65AVTGNvTajBu0BOxbkVw==,iv:7Dm53H9FDuvhEdn950J8reF0QVbF7vWo1Z7jtaU1IKI=,tag:gIm8n/C2PqjBalEzx39UNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-09T19:56:50Z"
    mac: ENC[AES256_GCM,data:gWBpsSDAgSUCjPEE2KN/il2ux8e911EwxWstsnyL7nX793KI/6ODA+br9Mz5VT625JD8x9UQ82IhxnQQQyKLH2uKit3WjrzpouzfNNif9Nf95+vm/+NFxgL/vZyiiTi5X4qK8VFAQxMRR/WcWMvTaan/HgdQpOO/hJZbN/J4YHY=,iv:ioJX1fh7pv5FdlLlTDImqMz5ufyxrpB4du4k6IyJbT8=,tag:ywGulIyCidmi0V0EhB3P4g==,type:str]
    pgp:
        - created_at: "2021-07-09T19:31:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv9G0Jr8dIMGQuT9D8CsifLmYjAK/Dkr98X0+RfuIv9GAGC
            PufH3ncc4z7IB4wjRjSgqxZ0Uh3Nmdj2MO3tj9WzNzT9whz/OVfOM/J1tJ659qJD
            k07pYtkSWOxtUOzT+AzKnFEXvSNCzMyRECr+qPh+q+mjPaE3IApBNLf23Tcq0ILs
            HIp7f5u5xJXoc8fW3CSdv9qXXjmMjOGbl5SQYFRGDMr9yS7Fv3MKSHaksdf+tPEb
            Qa0oKxPPMUBKDi+crFa2+ZEVoqS2M2wWriEbSzVjTkQkLGKvKLvVU2Dbz/JmRpu7
            VH735LIU6ldGH/oiS/WwPFzJln3Yq+imd1PEpdgIf2+2jpWPk3ACj7K6MPMsE7SX
            WIALh/X8ccyWMdxeACofq+85ZE6vnrOhINo4AmxClOJoygC6AMP/2vblYbEzL4Vh
            nfsgu8AagU26jGNjnJO8fxrK/6RIIST6osK2YrZXmKH0WskBnkq0gIeqHcpVoIPc
            4VHZZO63Vx/W+gFn4xld0l4BMZaly9rBBL/7atylDWVQn+LzQP0UTCBwXXGm52vd
            s4e5Xw9gY2JfzR5jZo1CO24SFhf/g10gQVl9PYjC8AmwFDDXrTWkPpitTNJ0IMEH
            JBs/G7lL6U3sLoJgHpvO
            =6ncv
            -----END PGP MESSAGE-----
          fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    unencrypted_suffix: _unencrypted
    version: 3.7.1
