---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://halkeye.github.io/helm-charts/
      chart: whoami
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: halkeye
        namespace: flux-system
  values:
    replicaCount: 3
    ingress:
      enabled: true
      tls:
        - hosts: [whoami.netsoc.tcd.ie]
          secretName: tls-tcd
      hosts: [whoami.netsoc.tcd.ie]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
