---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami
spec:
  interval: 1m
  chart:
    spec:
      chart: whoami
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: halkeye
        namespace: flux-system
  values:
    replicaCount: 3
    ingress:
      enabled: true
      tls:
        - hosts: [docs.staging.netsoc.ie]
          secretName: tls-staging
      hosts: [whoami.netsoc.tcd.ie]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
