config:
    connectors:
        - type: iamd
          id: iam
          name: Netsoc IAM
          config:
            url: http://iamd.default/v1
            token: ENC[AES256_GCM,data:eVkPA4/n2KUkglgZk32XJTGcZvOX+/+tLSFnGWEUS10sn1JBZ3DqP6QNd12Sd/wsPugdqXwGWK+jIvPXpkAb0zFawoNr2fwSFTl4B+GtJJDvK3A+4ku4oeHf5OrtX1oe8zg61CP6K6W9Jj/AXTXlU0f8WGU4XheMWUtIua2FypTPOL9FbhW7hxtlKJv/JUPmJeuExzzezEtDXv8SJKLFNVMx1rVKmh4RMpj3thoc76tmHoJYolrog33TliV9O0OpAweeyz8VdWHCbgenfNyCQ+OTxLytgeCbqoB13jH0U5+qPH5lgV9BUo43nYny1Wvp5nMITmuyCLR98OckDfDU0qGJMi7/9YfwbPZaQE8=,iv:j+wOiw9BjNfqoTkhON3f61wC+lxRcatiYa2TPmTlwmk=,tag:fcMBtXhArwVcR9sjrlEQ2g==,type:str]
            prompt: Netsoc username
    staticClients:
        - id: gitea
          name: Gitea
          redirectURIs:
            - http://git.netsoc.ie/user/oauth2/netsoc/callback
          secret: ENC[AES256_GCM,data:F2X//5U8U9erjTMr1RhRtf252MRxuNd7jAWMLzOJ1Pg=,iv:YUWsEXqhPLs5Pgmrryq0OcUlPBBHZ699rEAo+BTTeyU=,tag:OMH1eaKzDSaqYLCBDsKk6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T01:31:42Z"
    mac: ENC[AES256_GCM,data:64VXX4f1Hmrllypn+tDMcEyaMnfoSYWz822ba5dTmWJxu5w81inoue61MJV1XJjKkOnG1aa7hhaNTMyqVG698oN1WaqcYwbgsTUZhZcbaWqynVHdA2sHzts0L3usj8kWErnt9DHg/0+eQXLoYKUHviVEjQ1o7jRsT9v517h/XiU=,iv:B5wFQFaDBNgQhYDwcWi6ISmJJ3B83uf4HvBvIJCxrEk=,tag:oN1rdM5o4f7uevqZfZD+0g==,type:str]
    pgp:
        - created_at: "2021-07-30T01:28:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv/RCE/snYNQXbsaCcAVJUBoehOobkPEaDC8Fq1p5ZwPEVS
            a4WTsyGDnf0SxGXNsjg3/bwWLo8U+c7MG9oz4TbGFFqJW2MuqcvkVp1ye1Eqfbyv
            V3CHf81krzFsoNUMp/LwLt/gqQEw/7ow8jXVdiYfK8Hh5rnx/WoIAl1NUrlJARWO
            l2raGDbFaMkVYIvnNbbTXAiF0JHsKKxzK7vzK9GZraq4fFhiryw7fskXP5ZwmILP
            NFYOppOXMop9o8pWtZLsVj6mlpeh01CrUp5KTvdEoy4Rn1zdtbrIRcpewIwmaGoC
            tAvWJuV9CQ3wH5OG0TyQM4OZl41Fv1up3uRdKC/AR0pSXZFd7jP2K7qr8d6Ubt/4
            g7N8rZ4PzaC4KIKkDXO+ebB8HWXSQcBzhCUeY6KplBO7JO4z8/3J7w/YIj/1qtGi
            MKClfJSey/vVW7ws3kraOD8JeLB8MIHAPOqLbWnkkvVuYlyojycaZMX+DN7LGlLZ
            Je3NiRxBTQqMIa2CLlVt0l4B/mq6/VUuwL3IV5exNwl75IJlciFj8JH82yMnYzDV
            6vja+d78PS+BAYhLvZO+fM3IN5ulxlLRC7E8BxT7w47rhQrIiiUt5Nu+Dqrsj+/z
            c/fG/qzzQIy5SVy1vVD+
            =++1U
            -----END PGP MESSAGE-----
          fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    encrypted_regex: (token|secret)
    version: 3.7.1
