config:
    connectors:
        - type: iamd
          id: iam
          name: Netsoc IAM
          config:
            url: http://iamd.default/v1
            token: ENC[AES256_GCM,data:Xu8Wwq0uQ564A9EXYkcRB4S2vPQdX4ja+YGR9w88duJyESr9mtCn7ZC4+cPjcDDXW7q+kxalcPkPfZ/OcG456BGycKWnnXIa3CElG+kxFFgiJ9yqSiC6m8+EPU1KALxDXOxYPTY1KNUZ03U+hKBIfKCsHOdhkIqG+jJGxlBkHq7j3F6qZkAUHkYf2SiAlHmHT0hWJlKWJ1RflG6nf2E/u1atV6HeTxMPU7OYRJXIk2GzNGzQYG0zfgvuUli6wE6ZGrzWC0M8iohGLri/56zZER6TXAW/UgD13Wuyj2dxnd+6GKiUkkL1we2dJuLY7YcSu4HnWKKQ8F3aY+hkNh+tlS3bAMF9l2yHMTFECag=,iv:81wQ3hGYXBape7SQIzllOFOtghprJHCNKvY4eV5uCEk=,tag:sNtTfMNetcavJldkrXxMCA==,type:str]
            prompt: Netsoc username
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-29T15:10:44Z"
    mac: ENC[AES256_GCM,data:x2QdFhF6w7BdoNkFqHmL/gBBUgHclDrAioGAPE9QSrpbGj4Hk2bzhpjkCyEUUNIl6PExKXnaBkSrwTSK5pVGKXriMe3EPc20IDRhQogKIJdlth/S3fZVx9GFiGmPvSx4WLRMVRReuwAuej4+pOPqMl85CEV8NvSqGmgvgZksRUs=,iv:WIuR654jqnWXXtNx6ATuZ+fyTRY0CNgNb5nWoJscWYQ=,tag:IYnW/z8dFC5ps1n+ZK/PEA==,type:str]
    pgp:
        - created_at: "2021-07-29T15:10:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv+JLYwi/vUJffG32dtRTgs2J7MKeULonvYCKsdMSpu044i
            hpoaXjyiZzGAmM5BDUGNdFIThfqDLea4NKvmsY8WJCulTBAVGCKhFiOFhYB0bNff
            YhJJoKFSSLHdUcWzrqm6rRlUH4wudgg7jPbtVzvHfWjO+Tj/4yVgszKdmgMdrLaK
            7VY8K50kirC4zGrXyD28HDUXkFtPu9yiSVzld7sOlTnIs48D2jWg2SPxVrUT67Je
            oqwk2aCwOzKWI0y8I5LZp7LxpcGLa9RZ+x/IFhkYmJnhZqmnALCCMJ5iT0fMprlF
            +hmNvGt2PPmOQ7uCkbIj2E7S/lQD8qoigR//rEwlP/v96zhjI8BIhGS6KD+b2Uu+
            0ZEfEfOE0Pk/aKK3sg6mgQ4zTpa3TG73REfkspg68YAWPbBnD0PtNxSf6gG/85hQ
            zdjXEupKl674KcZ6JB/gOqQo2rLK9XjDoS4C98kPWeYxTc4WWurualIpHwId31sA
            k/qKjipmN42SGrm2MndP0lwBm/MZNgcKniWahPATndm6rgiAHpioj2o9s3j9/BGp
            McRCvSOFJSFoF9iK8/Twnp7kyjIhvXuJ5tymGZxzBtk4KeZBQ20eTsXciJIqSpzT
            aID835drV7LW3Wg/qg==
            =YUKd
            -----END PGP MESSAGE-----
          fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    encrypted_regex: token
    version: 3.7.1
