apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- pvc-lxd.yaml
#- pvc-storage.yaml
- helm.yaml
secretGenerator:
- name: lxd8s-extras
  files:
  - trustPassword=secrets/trust_password.bin
