---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 9.17.x
  install:
    skipCRDs: true
  values:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetes:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        protocol: TCP
        port: 8080
        expose: true
        exposedPort: 80
        redirectTo: websecure
      websecure:
        protocol: TCP
        port: 8443
        expose: true
        exposedPort: 443
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: http
      spec:
        loadBalancerIP: '134.226.83.100'
        externalTrafficPolicy: Local
    ingressRoute:
      dashboard:
        # We want to offer the dashboard on a custom host with auth
        enabled: false
    deployment:
      replicas: 1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`traefik.netsoc.tcd.ie`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: auth
  tls:
    secretName: tls-tcd
    domains:
    - main: '*.netsoc.tcd.ie'
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  basicAuth:
    secret: traefik-ops-users
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-redirect
spec:
  redirectRegex:
    regex: '^https://traefik.netsoc.tcd.ie/(.*)'
    replacement: 'https://traefik.netsoc.tcd.ie/dashboard/${1}'
    permanent: true
