---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    skipCRDs: true
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/netsoc/traefik
            newTag: 2.5.0-rc2-5be7f6a2
  values:
    image:
      name: ghcr.io/netsoc/traefik
      # The chart uses semverCompare which ignores "pre-releases" by default (a "+" can't be in a docker ref), so we
      # patch the real version in with kustomize (see above)
      tag: 2.5.0

    logs:
      general:
        level: INFO
      access:
        enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetes:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        protocol: TCP
        port: 80
        expose: true
        redirectTo: websecure
      websecure:
        protocol: TCP
        port: 443
        expose: true
      lxd:
        protocol: TCP
        port: 8443
        expose: true
    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: http
      spec:
        loadBalancerIP: '134.226.83.100'
        externalTrafficPolicy: Local
    ingressRoute:
      dashboard:
        # We want to offer the dashboard on a custom host with auth
        enabled: false

    securityContext:
      capabilities:
        add: [NET_BIND_SERVICE]
        drop: [ALL]
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
    deployment:
      replicas: 1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`traefik.netsoc.tcd.ie`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: auth
  tls:
    secretName: tls-tcd
    domains:
    - main: '*.netsoc.tcd.ie'
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  basicAuth:
    secret: traefik-ops-users
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-redirect
spec:
  redirectRegex:
    regex: '^https://traefik.netsoc.tcd.ie/(.*)'
    replacement: 'https://traefik.netsoc.tcd.ie/dashboard/${1}'
    permanent: true
