apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm.yaml
secretGenerator:
- namespace: kube-system
  name: traefik-ops-users
  files:
  - users=users.htpasswd
configurations:
- secret-refs.yaml
