apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm.yaml
secretGenerator:
- name: traefik-ops-users
  files:
  - users=secrets/users.htpasswd
configurations:
- secret-refs.yaml
