apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- providers.yaml
- alerts.yaml
secretGenerator:
- name: github-token
  files:
  - token=secrets/github-token.bin
- name: matrix-webhook
  files:
  - address=secrets/matrix-webhook.bin
