---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: powerdns-postgresql
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 2Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: powerdns-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-postgresql-0
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  volumeName: powerdns-postgresql
  storageClassName: longhorn
