---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: powerdns-postgres
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 2Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: powerdns-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-postgres
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  volumeName: powerdns-postgres
  storageClassName: longhorn
