---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns-admin
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: powerdnsadmin
      version: 0.3.x
      sourceRef:
        kind: HelmRepository
        name: halkeye
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: powerdns-admin-secrets
  values:
    db:
      type: postgres
      host: powerdns-postgresql
      username: pdns
      database: pdns
    ingress:
      enabled: true
      hosts:
        - host: pdns.netsoc.tcd.ie
          paths: [/]
      tls:
        - hosts: [pdns.netsoc.tcd.ie]
          secretName: tls-tcd
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-auth@kubernetescrd
