---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iamd-postgresql
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 2Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: iamd-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iamd-postgresql
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  volumeName: iamd-postgresql
  storageClassName: longhorn
