apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docs
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: docs
      version: 0.1.x
      sourceRef:
        kind: HelmRepository
        name: netsoc
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/netsoc/docs
      tag: ff8a38bc-1623439837Z # {"$imagepolicy": "flux-system:docs:tag"}
    replicaCount: 1
    ingress:
      enabled: true
      tls:
      - hosts: [docs.staging.netsoc.ie]
        secretName: tls-staging
      hosts:
      - host: docs.staging.netsoc.ie
        paths: [/]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
