apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ma1sd
spec:
  interval: 1m
  chart:
    spec:
      chart: ma1sd
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: netsoc
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: ma1sd
    config:
      matrix:
        domain: 'staging.netsoc.ie'
      server:
        publicUrl: 'https://matrix.staging.netsoc.ie'

      dns:
        overwrite:
          homeserver:
            client:
              - name: 'matrix.staging.netsoc.ie'
                value: 'http://synapse-matrix-synapse:8008'
              - name: 'staging.netsoc.ie'
                value: 'http://synapse-matrix-synapse:8008'

      rest:
        enabled: true
        host: http://iamd.default:8008
