---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ma1sd
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 128Mi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: ma1sd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ma1sd
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 128Mi
  volumeName: ma1sd
  storageClassName: longhorn
