---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.4.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    skipCRDs: true
  values:
    installCRDs: false
    extraArgs:
      - '--dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53'
