nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: ClusterIssuer
    path: spec/acme/privateKeySecretRef/name
  - kind: ClusterIssuer
    path: spec/acme/solvers/dns01/rfc2136/tsigSecretSecretRef/name
