apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- _namespace.yaml
- longhorn.yaml
secretGenerator:
- name: dev-s3
  envs:
  - dev-s3.env
  files:
  - AWS_SECRET_ACCESS_KEY=secrets/dev-s3-key.bin
  options:
    disableNameSuffixHash: true
