apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- powerdns-pvc.yaml
- powerdns.yaml
- powerdns-admin.yaml
secretGenerator:
- name: dns-secrets
  files:
  - dbPassword=secrets/db-password.txt
  - powerdns-values.yaml=secrets/powerdns.yaml
