---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns
spec:
  suspend: true
  interval: 5m
  chart:
    spec:
      chart: powerdns
      version: 3.1.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: dns-secrets
      valuesKey: dbPassword
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: dns-secrets
      valuesKey: dbPassword
      targetPath: powerdns.postgres.password
    - kind: Secret
      name: dns-secrets
      valuesKey: powerdns-values.yaml
  values:
    env:
      TZ: Europe/Dublin
    postgresql:
      enabled: true
      persistence:
        enabled: true
        size: 2Gi
      volumePermissions:
        enabled: true
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: '134.226.83.27'
      annotations:
        metallb.universe.tf/allow-shared-ip: dns
    powerdns:
      domain: netsoc.tcd.ie
      config:
        default-ttl: 60
        allow-axfr-ips: '10.69.0.0/16,134.226.0.0/16'
        dnsupdate: yes
        allow-dnsupdate-from: ''
        resolver: '127.0.0.1'
        expand-alias: yes
