---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: powerdns
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: dns-secrets
      valuesKey: dbPassword
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: dns-secrets
      valuesKey: dbPassword
      targetPath: powerdns.postgres.password
    - kind: Secret
      name: dns-secrets
      valuesKey: powerdns-values.yaml
  values:
    replicaCount: 3
    env:
      TZ: Europe/Dublin

    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: powerdns-postgresql
      volumePermissions:
        enabled: true
      initdbScripts:
        # Separate DB for powerdns-admin
        powerdns-admin.sql: |
          CREATE DATABASE powerdnsadmin;
          GRANT ALL PRIVILEGES ON DATABASE powerdnsadmin to pdns;

    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: '134.226.83.27'
      annotations:
        # Enables both the UDP and TCP services to share the same IP
        metallb.universe.tf/allow-shared-ip: dns

    powerdns:
      domain: netsoc.tcd.ie
      config:
        default-ttl: 60
        allow-axfr-ips: '10.69.0.0/16,134.226.0.0/16'
        # Allow dynamic DNS updates, but only when authenticated
        dnsupdate: yes
        allow-dnsupdate-from: ''
        resolver: '127.0.0.1'
        # Serve up As for any ALIAS records, even for AXFRs
        expand-alias: yes
        outgoing-axfr-expand-alias: yes
        # Prevent IPVS connection drops
        gpgsql-extra-connection-parameters: keepalives=1 keepalives_idle=60 keepalives_interval=10 keepalives_count=3
