---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: powerdns
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: powerdns
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: dns-secrets
      valuesKey: dbPassword
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: dns-secrets
      valuesKey: dbPassword
      targetPath: powerdns.postgres.password
    - kind: Secret
      name: dns-secrets
      valuesKey: powerdns-values.yaml
  values:
    replicaCount: 3
    env:
      TZ: Europe/Dublin

    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: powerdns-postgresql
      volumePermissions:
        enabled: true
      initdbScripts:
        powerdns-admin.sql: |
          CREATE DATABASE powerdnsadmin;
          GRANT ALL PRIVILEGES ON DATABASE powerdnsadmin to pdns;

    service:
      type: LoadBalancer
      # Unfortunately we'll lose source IP with this, but Local is awkward and breaks internal access :(
      # https://github.com/kubernetes/kubernetes/pull/97081
      # https://github.com/kakao/network-node-manager
      externalTrafficPolicy: Local
      loadBalancerIP: '134.226.83.27'
      annotations:
        metallb.universe.tf/allow-shared-ip: dns

    powerdns:
      domain: netsoc.tcd.ie
      config:
        default-ttl: 60
        allow-axfr-ips: '10.69.0.0/16,134.226.0.0/16'
        dnsupdate: yes
        allow-dnsupdate-from: ''
        resolver: '127.0.0.1'
        expand-alias: yes
        outgoing-axfr-expand-alias: yes
        gpgsql-extra-connection-parameters: keepalives=1 keepalives_idle=60 keepalives_interval=10 keepalives_count=3
