apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docs
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://netsoc.github.io/charts/
      chart: docs
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: netsoc
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/netsoc/docs
      tag: fe18cd07-1629740924Z # {"$imagepolicy": "flux-system:docs:tag"}
    replicaCount: 1
    ingress:
      enabled: true
      tls:
        - hosts: [docs.netsoc.ie]
          secretName: tls-main
      hosts:
        - host: docs.netsoc.ie
          paths:
            - path: /
              pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
