---
apiVersion: v1
kind: Service
metadata:
  name: mail
spec:
  type: ExternalName
  externalName: mail.netsoc.internal
  ports:
    - name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail
spec:
  rules:
    - host: mail.netsoc.tcd.ie
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mail
                port:
                  name: http
  tls:
    - hosts: [mail.netsoc.tcd.ie]
      secretName: tls-tcd
