apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: website
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://netsoc.github.io/charts/
      chart: website
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: netsoc
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/netsoc/website
      tag: f7a1ee5e-1636818488Z # {"$imagepolicy": "flux-system:website:tag"}
    replicaCount: 1
    ingress:
      enabled: true
      tls:
        - hosts: [www.netsoc.ie]
          secretName: tls-main
      hosts:
        - host: www.netsoc.ie
          paths:
            - path: /
              pathType: Prefix
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.middlewares: 'default-meetings-redirect@kubernetescrd,default-events-redirect@kubernetescrd,default-cli-redirect@kubernetescrd'

# Handy shortcuts
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cli-redirect
spec:
  redirectRegex:
    regex: '^https://www.netsoc.ie/cli/?$'
    replacement: 'https://github.com/netsoc/cli/releases/latest'
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: meetings-redirect
spec:
  redirectRegex:
    regex: '^https://www.netsoc.ie/meeting/?$'
    replacement: 'https://tcd-ie.zoom.us/j/97182874403?pwd=ZW9CSHdEZTVRSWVOMmZsU3hsbVRwdz09'
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: events-redirect
spec:
  redirectRegex:
    regex: '^https://www.netsoc.ie/event/?$'
    replacement: 'https://tcd-ie.zoom.us/j/8820425304?pwd=OFdSK3M3UWJDRkZ1NXlUbTBicFNodz09'
    permanent: true

# Redirect from netsoc.ie -> www.netsoc.ie
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
spec:
  redirectRegex:
    regex: '^https://netsoc.ie/(.*)'
    replacement: 'https://www.netsoc.ie/${1}'
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: www-redirect
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`netsoc.ie`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: www-redirect
          namespace: default
  tls:
    secretName: tls-main
    domains:
      - main: 'netsoc.ie'
        sans:
          - '*.netsoc.ie'

# Redirect *.netsoc.tcd.ie -> *.netsoc.ie
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: tcd-redirect
spec:
  redirectRegex:
    regex: '^https://(.*)netsoc.tcd.ie/(.*)'
    replacement: 'https://${1}netsoc.ie/${2}'
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tcd-redirect
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`netsoc.tcd.ie`) || Host(`www.netsoc.tcd.ie`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: tcd-redirect
          namespace: default
  tls:
    secretName: tls-tcd
    domains:
      - main: 'netsoc.tcd.ie'
        sans:
          - '*.netsoc.tcd.ie'
