---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 9.8.x
  values:
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetes:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        protocol: TCP
        port: 8080
        expose: true
        exposedPort: 80
        redirectTo: websecure
      websecure:
        protocol: TCP
        port: 8443
        expose: true
        exposedPort: 443
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        loadBalancerIP: '192.168.76.10'
        #externalTrafficPolicy: Local
    ingressRoute:
      dashboard:
        enabled: false
    deployment:
      replicas: 1
