apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager
- kube-system
- metallb-system
- longhorn-system
- default
secretGenerator:
- namespace: kube-system
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
- namespace: longhorn-system
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
configurations:
- secret-refs.yaml
