apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metallb-system
- longhorn-system
- cert-manager
- kube-system
- default
- monitoring
- extra.yaml
- webspaces.yaml
secretGenerator:
- namespace: kube-system
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
  options:
    disableNameSuffixHash: true
- namespace: longhorn-system
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
  options:
    disableNameSuffixHash: true
- namespace: default
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
  options:
    disableNameSuffixHash: true
- namespace: monitoring
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
  options:
    disableNameSuffixHash: true
- namespace: extra
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
  options:
    disableNameSuffixHash: true
- namespace: webspaces
  name: tls-tcd
  type: kubernetes.io/tls
  files:
  - tls.crt=common/netsoc.tcd.ie.crt
  - tls.key=common/netsoc.tcd.ie.key
  options:
    disableNameSuffixHash: true
configurations:
- namerefs.yaml
