nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    path: spec/valuesFrom/name
  - kind: IngressRoute
    path: spec/tls/secretName
  - kind: HelmRelease
    path: spec/values/ingress/tlsSecret
