apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: element-web
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts/
      chart: element-web
      version: 1.0.30
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
  values:
    extraVolumes:
      - name: overlay
        configMap:
          name: element-web-overlay
    extraVolumeMounts:
      - name: overlay
        mountPath: /app/overlay

    defaultServer:
      url: https://matrix.netsoc.ie
      name: netsoc.ie
      identity_server: https://matrix.netsoc.ie

    config:
      disable_custom_urls: true
      disable_guests: true
      disable_3pid_login: false

      brand: Netsoc
      branding:
        welcomeBackgroundUrl: 'https://www.netsoc.ie/assets/images/matrix/bg.svg'
        authHeaderLogoUrl: 'https://www.netsoc.ie/assets/images/matrix/logo.png'
        authFooterLinks:
          - text: Manage my Netsoc account
            url: https://accounts.netsoc.ie/

      embeddedPages:
        welcomeUrl: '/overlay/welcome.html'

      welcomeUserId: ''
      defaultCountryCode: IE
      showLabsSettings: true

    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
      hosts: [matrix.netsoc.ie]
      tls:
        - secretName: tls-main
          hosts: [matrix.netsoc.ie]
