apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm.yaml
configMapGenerator:
- name: element-web-overlay
  files: [welcome.html]
  options:
    disableNameSuffixHash: true
