---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crds
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./crds
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
spec:
  dependsOn:
    - name: crds
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: pgp
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: metallb-system
      name: metallb
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: longhorn-system
      name: longhorn
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: cert-manager
      name: cert-manager
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: kube-system
      name: traefik
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: default
      name: powerdns
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: default
      name: powerdns-admin
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      namespace: monitoring
      name: dashboard
