apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kube-system
- metallb-system
- cert-manager
- longhorn-system
- monitoring
- default
configurations:
- kustomize-helm-values.yaml
