apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: accounts
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://netsoc.github.io/charts/
      chart: accounts
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: netsoc
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: accounts-secrets
  values:
    ingress:
      enabled: true
      tls:
      - hosts: [accounts.netsoc.ie]
        secretName: tls-main
      hosts: [accounts.netsoc.ie]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'

    frontend:
      config:
        IAM_BASE_URL: 'https://iam.netsoc.ie/v1'
        PAYMENT_BASE_URL: https://accounts.netsoc.ie/api
        STRIPE_PUBLIC_KEY: 'pk_test_514gI43BPJxpSdBx8esUHmCoU4mRICB29h5HewGIMpiARXL8IFcDMNpqM7ztJqPOotPvKkobkwIC0fSymYNbL9KGn000DMtyT58'
        MAIN_WEBSITE_URL: 'https://www.netsoc.ie/services/'

    backend:
      config:
        ACCOUNTS_BASE_URL: https://accounts.netsoc.ie
        IAM_BASE_URL: http://iamd/v1
