apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synapse
spec:
  interval: 1m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts/
      chart: matrix-synapse
      version: 2.1.14
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: synapse-extras
  values:
    signingkey:
      job:
        enabled: false
      existingSecret: synapse-extras
      existingSecretKey: signing.key

    serverName: netsoc.ie
    publicServerName: matrix.netsoc.ie

    config:
      logLevel: INFO

      enableRegistration: false

    extraConfig:
      max_upload_size: 128M
      max_image_pixels: 32M

      url_preview_enabled: true
      url_preview_ip_range_blacklist:
        - '127.0.0.0/8'
        - '10.0.0.0/8'
        - '172.16.0.0/12'
        - '192.168.0.0/16'
        - '100.64.0.0/10'
        - '192.0.0.0/24'
        - '169.254.0.0/16'
        - '192.88.99.0/24'
        - '198.18.0.0/15'
        - '192.0.2.0/24'
        - '198.51.100.0/24'
        - '203.0.113.0/24'
        - '224.0.0.0/4'
        - '::1/128'
        - 'fe80::/10'
        - 'fc00::/7'
        - '2001:db8::/32'
        - 'ff00::/8'
        - 'fec0::/10'

      allow_guest_access: false
      trusted_third_party_id_servers: [matrix.netsoc.ie]
      password_providers:
        - module: rest_auth_provider.RestAuthProvider
          config:
            endpoint: 'http://ma1sd:8090'
            policy:
              registration:
                profile:
                  name: true
              login:
                profile:
                  name: false

    synapse:
      extraCommands:
        - apt-get update -qyy && apt-get install curl unzip -yqq
        - curl -Lo /tmp/rest-provider.zip https://github.com/devplayer0/matrix-synapse-rest-password-provider/archive/master.zip
        - cd /tmp && unzip rest-provider.zip
        - cd /tmp/matrix-synapse-rest-password-provider-master && python setup.py install
      livenessProbe:
        # Give the extra commands a chance to run
        initialDelaySeconds: 30

    workers:
      default:
        extraCommands:
          - apt-get update -qyy && apt-get install curl unzip -yqq
          - curl -Lo /tmp/rest-provider.zip https://github.com/devplayer0/matrix-synapse-rest-password-provider/archive/master.zip
          - cd /tmp && unzip rest-provider.zip
          - cd /tmp/matrix-synapse-rest-password-provider-master && python setup.py install
        livenessProbe:
          # Give the extra commands a chance to run
          initialDelaySeconds: 30
      generic_worker:
        enabled: true
        replicaCount: 2
        csPaths: # Set all of these since the login endpoint should be overridden by ma1sd
        # - "/_matrix/client/(v2_alpha|r0)/sync"
          - "/_matrix/client/(api/v1|v2_alpha|r0)/events"
        # - "/_matrix/client/(api/v1|r0)/initialSync"
        # - "/_matrix/client/(api/v1|r0)/rooms/[^/]+/initialSync"
          - "/_matrix/client/(api/v1|r0|unstable)/publicRooms"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/joined_members"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/context/.*"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/members"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/state"
          - "/_matrix/client/(api/v1|r0|unstable)/account/3pid"
          - "/_matrix/client/(api/v1|r0|unstable)/keys/query"
          - "/_matrix/client/(api/v1|r0|unstable)/keys/changes"
          - "/_matrix/client/versions"
          - "/_matrix/client/(api/v1|r0|unstable)/voip/turnServer"
          - "/_matrix/client/(api/v1|r0|unstable)/joined_groups"
          - "/_matrix/client/(api/v1|r0|unstable)/publicised_groups"
          - "/_matrix/client/(api/v1|r0|unstable)/publicised_groups/"
        # - "/_matrix/client/(api/v1|r0|unstable)/login"
          - "/_matrix/client/(r0|unstable)/register"
          - "/_matrix/client/(r0|unstable)/auth/.*/fallback/web"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/send"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/state/"
          - "/_matrix/client/(api/v1|r0|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)"
          - "/_matrix/client/(api/v1|r0|unstable)/join/"
          - "/_matrix/client/(api/v1|r0|unstable)/profile/"
      pusher:
        enabled: true
      federation_sender:
        enabled: true
      media_repository:
        enabled: true
        strategy:
          type: Recreate
      frontend_proxy:
        enabled: true

    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: synapse-postgresql
      volumePermissions:
        enabled: true

    redis:
      enabled: true

    persistence:
      enabled: true
      existingClaim: synapse-media
    volumePermissions:
      enabled: true

      image:
        repository: alpine
        tag: latest
        pullPolicy: Always

    service:
      port: 8008

    ingress:
      enabled: true
      traefikPaths: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

      includeServerName: true
      includeUnderscoreSynapse: true

      hosts: [matrix.netsoc.ie]
      csHosts: [matrix.netsoc.ie]

      paths:
        - path: /_matrix/identity
          backend:
            serviceName: ma1sd
            servicePort: 8090
      csPaths:
        - path: /_matrix/identity
          backend:
            serviceName: ma1sd
            servicePort: 8090
        - path: /_matrix/client/r0/user_directory
          backend:
            serviceName: ma1sd
            servicePort: 8090
        - path: /_matrix/client/r0/login
          backend:
            serviceName: ma1sd
            servicePort: 8090

      tls:
        - secretName: tls-main
          hosts: [matrix.netsoc.ie]
