---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-media
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 128Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: synapse-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-media
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 128Gi
  volumeName: synapse-media
  storageClassName: longhorn
