postgresql:
    postgresqlPassword: ENC[AES256_GCM,data:CGm18evUasvlV9oyEvy4vQ==,iv:c8q6NSQBXU6hrPxYIR3NdnJngOSTgh0zk/8qq5wRHhs=,tag:ouPbwQE43Lburxw6W5zrTA==,type:str]
secrets:
    smtpPassword: ENC[AES256_GCM,data:Z+LlRAol9wasAbVVEn2WNg==,iv:9YbLRllqBYfH2YWRe4FoMheBvqBlvTToKhs29u6FKck=,tag:MSVso/OxaeTI8ZTpJjTyiA==,type:str]
    jwtKey: ENC[AES256_GCM,data:LF9edzTLkUh7/1OYCZGIos5pAkL1jpysZGycf14H/NEhDz6q7yR+/kmR6TM=,iv:WJ+UhAm6qqzPXeNoimvUOclYN9Mi+pV3T+HR6YMWVKk=,tag:weaagqbXKJJGLX/8EtunLg==,type:str]
    rootPassword: ENC[AES256_GCM,data:Wkbc+UVF3Mn/3FfgLVwk/Q==,iv:7rkGEnzKjqt4z1p7zJ3Jee3Rzpy+pTBJ7xacfi+TO8g=,tag:QoCOGVUmv+Qj2+aZfI8kgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-29T00:50:26Z"
    mac: ENC[AES256_GCM,data:sCA7KmhQEUIXRR4fAAB3YAJM3LV+1uJ/9Mz3XHJmox5dlvzMmJJhM7iUBdDCecJtnJAcDeEOLkqNoupz7iHuC2wBbl6rXiGI7JjPWiTAdb/HlUVNTJp+FiaRVZdG2g20Ie4tkz+1XhEkkVzjyI/5/Vbd4LNq3SX2q3cZvRSgT+g=,iv:zDb1ozq9rFoMP9Muk6Jz3O7qvpoZe3/nbpm4xJKD48o=,tag:7Cj/a5jD74kZZvTmpYSrUg==,type:str]
    pgp:
        - created_at: "2021-06-15T00:42:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv+N6bOrMTIN5DWnhUydFHbe63LIAZ+z1powj8BXh8sliKr
            GdRhuLGf+UygTDC2KTUESlXiIujDZl9YzAFODvp9nbZ/d2rlQZ87rtogVkySDLFX
            oE8JoFIRqsb4HxW/tdgrD5lx+X3LSWmBfVfWc5Czk0gAc5K+U7Nn4hdJukpaYy1C
            CPveeMoOca7E/cYDkDeZx0PtqUA6baJmmZ5kFtd5O/kMX/phMIKyBtj/pc6N5gIB
            oa7F1TNmFzJqi2R23pq5RV1K5clRE+TJa1H73W6hwgt9C+HunFFdp1Vj5yqurOhI
            5xbOwYiadOpflhJvoqUdR6J5FXUQAs3rkKnEZBH3bN91am7vO4hSIfcQBJHnQ+hT
            xTq0N2B78gWZKlnh93xl6h3j5ljnVESvYyEeYyZDtcBEG3zj+hP4NXSFhfJFumb/
            7EJfwJzDRq2OkslDHrU8LDl+P0op1/B+D788DCX7AquCbIr6oEl2Y6pnHdPvrCv4
            LOltI0aQICUnKL4Pe+eh0l4BW5ZcpO9f/wZERCjsk5t37J9Wa3GA9rpy7k5KRdAs
            1oRoGL0/nz/mP4AJ0qeFtL5NkW+NRr2dgyskrt7Q4Qo2xcXi/jX9epg2XuLdKuzz
            lhVBaTYux38kSHx/+I4K
            =rxjW
            -----END PGP MESSAGE-----
          fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    unencrypted_suffix: _unencrypted
    version: 3.7.1
