postgresql:
    postgresqlPassword: ENC[AES256_GCM,data:SuAKdp9yQztYLjOJybnzGQ==,iv:0hS3afJcnMQ1IP4WwtOoOQZ+v0hr+jCFvXtLSkz0ew8=,tag:l05qRJ8GtTXnwZhXUCwPTw==,type:str]
secrets:
    smtpPassword: ENC[AES256_GCM,data:2SNlwq4DWPT1Mw==,iv:9duzWy5JUqE+E0ONbPnEWD4wionPV5j7FlhlEJ38EvM=,tag:xQhZBwH/bSK23724Ha9v9g==,type:str]
    jwtKey: ENC[AES256_GCM,data:ZUyH31AZlrT4L5RxBzQCLVZRioVdlt8fBpi0dryY8MfHc1ha+88rY79kvL0=,iv:gHFku7Rq6ZljQRrU55Gx9heEkEjQ3zaSFHgB6lLdzjI=,tag:hHvNsVxIAA2/y5q6v3vFFQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:L7qPR0LndEXl8Q8hYaiA8g==,iv:d1CkiPkz044QXgb6upIVun4SZAJZL5iX8zLP+QxkmrU=,tag:YukuQTgoAzwHqBcTVffD8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-29T20:50:10Z"
    mac: ENC[AES256_GCM,data:8yQ/nOax4XGAbXe8YRY1DiOOgUYbbyXdUSV1YGKj8OaADoFzLUL9okONgfi7XyLT+bqYREUpCKxSYtn0gGnjIIXYcGcn2PbJmwq3EnspvZlZ1V43DFlCe7pKtQ+Y/HhQE6AZj2KJbaKl1QlH3WxibSZOzwdsoqLMadCefesZrwo=,iv:wncR9g3hQaKRDJu7LDrxx2ESOxYkJK0gP6dusdj3mf0=,tag:qh/PFM1Pv2CEMeLoITCWBg==,type:str]
    pgp:
        - created_at: "2021-06-15T00:42:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv+N6bOrMTIN5DWnhUydFHbe63LIAZ+z1powj8BXh8sliKr
            GdRhuLGf+UygTDC2KTUESlXiIujDZl9YzAFODvp9nbZ/d2rlQZ87rtogVkySDLFX
            oE8JoFIRqsb4HxW/tdgrD5lx+X3LSWmBfVfWc5Czk0gAc5K+U7Nn4hdJukpaYy1C
            CPveeMoOca7E/cYDkDeZx0PtqUA6baJmmZ5kFtd5O/kMX/phMIKyBtj/pc6N5gIB
            oa7F1TNmFzJqi2R23pq5RV1K5clRE+TJa1H73W6hwgt9C+HunFFdp1Vj5yqurOhI
            5xbOwYiadOpflhJvoqUdR6J5FXUQAs3rkKnEZBH3bN91am7vO4hSIfcQBJHnQ+hT
            xTq0N2B78gWZKlnh93xl6h3j5ljnVESvYyEeYyZDtcBEG3zj+hP4NXSFhfJFumb/
            7EJfwJzDRq2OkslDHrU8LDl+P0op1/B+D788DCX7AquCbIr6oEl2Y6pnHdPvrCv4
            LOltI0aQICUnKL4Pe+eh0l4BW5ZcpO9f/wZERCjsk5t37J9Wa3GA9rpy7k5KRdAs
            1oRoGL0/nz/mP4AJ0qeFtL5NkW+NRr2dgyskrt7Q4Qo2xcXi/jX9epg2XuLdKuzz
            lhVBaTYux38kSHx/+I4K
            =rxjW
            -----END PGP MESSAGE-----
          fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    unencrypted_suffix: _unencrypted
    version: 3.7.1
