name: Renovate helpers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  helm_releases:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: '.'
          exclude-folders: 'docs,crds,flux'

      - name: Create pull request for renovatebot helm-release annotations
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: helm-renovate-annotations
          delete-branch: true
          title: 'chore(deps): update renovate annotations'
          committer: 'NetsocBot <internet@csc.tcd.ie>'
          author: 'NetsocBot <internet@csc.tcd.ie>'
          commit-message: 'chore(deps): update renovate annotations'
          body: |
            Update HelmReleases in order for Renovate to pick up new versions of Helm charts
          labels: renovate/helm-renovate-annotations
