---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 256Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 256Gi
  volumeName: gitea
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-postgresql
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 16Gi
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: gitea-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql
spec:
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 16Gi
  volumeName: gitea-postgresql
  storageClassName: longhorn
